version: '2'
services:
  dev:
    build: .
    image: keboola/docker-runner-2-poc
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: php ./run.php
    environment:
      - KBC_CONTAINER_MEMORY
      - KBC_CONTAINER_RUN_TIME
      - KBC_CONTAINER_TIMEOUT
  cli:
    build:
      context: ./cli
    working_dir: /code
    volumes:
      - ./cli:/code
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION

